// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "project.v2.proto" (package "project.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message project.v2.Project
 */
export interface Project {
    /**
     * @generated from protobuf field: string uuid = 1;
     */
    uuid: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: project.v2.Project.ScreenRatio ratio = 3;
     */
    ratio: Project_ScreenRatio;
    /**
     * @generated from protobuf field: int32 screenWidth = 4;
     */
    screenWidth: number;
    /**
     * @generated from protobuf field: int32 screenHeight = 5;
     */
    screenHeight: number;
    /**
     * @generated from protobuf field: repeated project.v2.Project.RegionOfInterest rois = 6;
     */
    rois: Project_RegionOfInterest[];
    /**
     * @generated from protobuf field: string OBSOLETE_dataURL = 7 [json_name = "OBSOLETEDataURL"];
     */
    oBSOLETEDataURL: string;
    /**
     * @generated from protobuf field: int32 version = 8;
     */
    version: number;
    /**
     * @generated from protobuf field: repeated project.v2.Project.Namespace namespaces = 9;
     */
    namespaces: Project_Namespace[];
    /**
     * @generated from protobuf field: bytes image = 10;
     */
    image: Uint8Array;
}
/**
 * @generated from protobuf message project.v2.Project.RegionOfInterest
 */
export interface Project_RegionOfInterest {
    /**
     * @generated from protobuf field: string uuid = 1;
     */
    uuid: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: int32 x = 3;
     */
    x: number;
    /**
     * @generated from protobuf field: int32 y = 4;
     */
    y: number;
    /**
     * @generated from protobuf field: int32 width = 5;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 6;
     */
    height: number;
    /**
     * @generated from protobuf field: project.v2.Project.RegionOfInterest.Anchor anchor = 7;
     */
    anchor: Project_RegionOfInterest_Anchor;
    /**
     * @generated from protobuf field: project.v2.Project.RegionOfInterest.Rect rect = 8;
     */
    rect?: Project_RegionOfInterest_Rect;
    /**
     * @generated from protobuf field: string namespace = 9;
     */
    namespace: string;
}
/**
 * @generated from protobuf message project.v2.Project.RegionOfInterest.Rect
 */
export interface Project_RegionOfInterest_Rect {
    /**
     * @generated from protobuf field: string uuid = 1;
     */
    uuid: string;
    /**
     * @generated from protobuf field: int32 x = 3;
     */
    x: number;
    /**
     * @generated from protobuf field: int32 y = 4;
     */
    y: number;
    /**
     * @generated from protobuf field: int32 width = 5;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 6;
     */
    height: number;
}
/**
 * @generated from protobuf enum project.v2.Project.RegionOfInterest.Anchor
 */
export enum Project_RegionOfInterest_Anchor {
    /**
     * @generated from protobuf enum value: CENTER = 0;
     */
    CENTER = 0,
    /**
     * @generated from protobuf enum value: TOP_LEFT = 1;
     */
    TOP_LEFT = 1,
    /**
     * @generated from protobuf enum value: TOP_RIGHT = 2;
     */
    TOP_RIGHT = 2,
    /**
     * @generated from protobuf enum value: BOTTOM_LEFT = 3;
     */
    BOTTOM_LEFT = 3,
    /**
     * @generated from protobuf enum value: BOTTOM_RIGHT = 4;
     */
    BOTTOM_RIGHT = 4,
    /**
     * @generated from protobuf enum value: CENTER_LEFT = 5;
     */
    CENTER_LEFT = 5,
    /**
     * @generated from protobuf enum value: CENTER_RIGHT = 6;
     */
    CENTER_RIGHT = 6,
    /**
     * @generated from protobuf enum value: CENTER_TOP = 7;
     */
    CENTER_TOP = 7,
    /**
     * @generated from protobuf enum value: CENTER_BOTTOM = 8;
     */
    CENTER_BOTTOM = 8
}
/**
 * @generated from protobuf message project.v2.Project.Namespace
 */
export interface Project_Namespace {
    /**
     * @generated from protobuf field: string uuid = 1;
     */
    uuid: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
}
/**
 * @generated from protobuf enum project.v2.Project.ScreenRatio
 */
export enum Project_ScreenRatio {
    /**
     * @generated from protobuf enum value: RATIO_FULL = 0;
     */
    RATIO_FULL = 0,
    /**
     * @generated from protobuf enum value: RATIO_1_2 = 1;
     */
    RATIO_1_2 = 1,
    /**
     * @generated from protobuf enum value: RATIO_3_4 = 2;
     */
    RATIO_3_4 = 2,
    /**
     * @generated from protobuf enum value: RATIO_9_16 = 3;
     */
    RATIO_9_16 = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class Project$Type extends MessageType<Project> {
    constructor() {
        super("project.v2.Project", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ratio", kind: "enum", T: () => ["project.v2.Project.ScreenRatio", Project_ScreenRatio] },
            { no: 4, name: "screenWidth", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "screenHeight", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "rois", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Project_RegionOfInterest },
            { no: 7, name: "OBSOLETE_dataURL", kind: "scalar", jsonName: "OBSOLETEDataURL", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "version", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "namespaces", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Project_Namespace },
            { no: 10, name: "image", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<Project>): Project {
        const message = { uuid: "", name: "", ratio: 0, screenWidth: 0, screenHeight: 0, rois: [], oBSOLETEDataURL: "", version: 0, namespaces: [], image: new Uint8Array(0) };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Project>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Project): Project {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* project.v2.Project.ScreenRatio ratio */ 3:
                    message.ratio = reader.int32();
                    break;
                case /* int32 screenWidth */ 4:
                    message.screenWidth = reader.int32();
                    break;
                case /* int32 screenHeight */ 5:
                    message.screenHeight = reader.int32();
                    break;
                case /* repeated project.v2.Project.RegionOfInterest rois */ 6:
                    message.rois.push(Project_RegionOfInterest.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string OBSOLETE_dataURL = 7 [json_name = "OBSOLETEDataURL"];*/ 7:
                    message.oBSOLETEDataURL = reader.string();
                    break;
                case /* int32 version */ 8:
                    message.version = reader.int32();
                    break;
                case /* repeated project.v2.Project.Namespace namespaces */ 9:
                    message.namespaces.push(Project_Namespace.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bytes image */ 10:
                    message.image = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Project, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* project.v2.Project.ScreenRatio ratio = 3; */
        if (message.ratio !== 0)
            writer.tag(3, WireType.Varint).int32(message.ratio);
        /* int32 screenWidth = 4; */
        if (message.screenWidth !== 0)
            writer.tag(4, WireType.Varint).int32(message.screenWidth);
        /* int32 screenHeight = 5; */
        if (message.screenHeight !== 0)
            writer.tag(5, WireType.Varint).int32(message.screenHeight);
        /* repeated project.v2.Project.RegionOfInterest rois = 6; */
        for (let i = 0; i < message.rois.length; i++)
            Project_RegionOfInterest.internalBinaryWrite(message.rois[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string OBSOLETE_dataURL = 7 [json_name = "OBSOLETEDataURL"]; */
        if (message.oBSOLETEDataURL !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.oBSOLETEDataURL);
        /* int32 version = 8; */
        if (message.version !== 0)
            writer.tag(8, WireType.Varint).int32(message.version);
        /* repeated project.v2.Project.Namespace namespaces = 9; */
        for (let i = 0; i < message.namespaces.length; i++)
            Project_Namespace.internalBinaryWrite(message.namespaces[i], writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* bytes image = 10; */
        if (message.image.length)
            writer.tag(10, WireType.LengthDelimited).bytes(message.image);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message project.v2.Project
 */
export const Project = new Project$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Project_RegionOfInterest$Type extends MessageType<Project_RegionOfInterest> {
    constructor() {
        super("project.v2.Project.RegionOfInterest", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "anchor", kind: "enum", T: () => ["project.v2.Project.RegionOfInterest.Anchor", Project_RegionOfInterest_Anchor] },
            { no: 8, name: "rect", kind: "message", T: () => Project_RegionOfInterest_Rect },
            { no: 9, name: "namespace", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Project_RegionOfInterest>): Project_RegionOfInterest {
        const message = { uuid: "", name: "", x: 0, y: 0, width: 0, height: 0, anchor: 0, namespace: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Project_RegionOfInterest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Project_RegionOfInterest): Project_RegionOfInterest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 x */ 3:
                    message.x = reader.int32();
                    break;
                case /* int32 y */ 4:
                    message.y = reader.int32();
                    break;
                case /* int32 width */ 5:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 6:
                    message.height = reader.int32();
                    break;
                case /* project.v2.Project.RegionOfInterest.Anchor anchor */ 7:
                    message.anchor = reader.int32();
                    break;
                case /* project.v2.Project.RegionOfInterest.Rect rect */ 8:
                    message.rect = Project_RegionOfInterest_Rect.internalBinaryRead(reader, reader.uint32(), options, message.rect);
                    break;
                case /* string namespace */ 9:
                    message.namespace = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Project_RegionOfInterest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 x = 3; */
        if (message.x !== 0)
            writer.tag(3, WireType.Varint).int32(message.x);
        /* int32 y = 4; */
        if (message.y !== 0)
            writer.tag(4, WireType.Varint).int32(message.y);
        /* int32 width = 5; */
        if (message.width !== 0)
            writer.tag(5, WireType.Varint).int32(message.width);
        /* int32 height = 6; */
        if (message.height !== 0)
            writer.tag(6, WireType.Varint).int32(message.height);
        /* project.v2.Project.RegionOfInterest.Anchor anchor = 7; */
        if (message.anchor !== 0)
            writer.tag(7, WireType.Varint).int32(message.anchor);
        /* project.v2.Project.RegionOfInterest.Rect rect = 8; */
        if (message.rect)
            Project_RegionOfInterest_Rect.internalBinaryWrite(message.rect, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* string namespace = 9; */
        if (message.namespace !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.namespace);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message project.v2.Project.RegionOfInterest
 */
export const Project_RegionOfInterest = new Project_RegionOfInterest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Project_RegionOfInterest_Rect$Type extends MessageType<Project_RegionOfInterest_Rect> {
    constructor() {
        super("project.v2.Project.RegionOfInterest.Rect", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Project_RegionOfInterest_Rect>): Project_RegionOfInterest_Rect {
        const message = { uuid: "", x: 0, y: 0, width: 0, height: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Project_RegionOfInterest_Rect>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Project_RegionOfInterest_Rect): Project_RegionOfInterest_Rect {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* int32 x */ 3:
                    message.x = reader.int32();
                    break;
                case /* int32 y */ 4:
                    message.y = reader.int32();
                    break;
                case /* int32 width */ 5:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 6:
                    message.height = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Project_RegionOfInterest_Rect, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* int32 x = 3; */
        if (message.x !== 0)
            writer.tag(3, WireType.Varint).int32(message.x);
        /* int32 y = 4; */
        if (message.y !== 0)
            writer.tag(4, WireType.Varint).int32(message.y);
        /* int32 width = 5; */
        if (message.width !== 0)
            writer.tag(5, WireType.Varint).int32(message.width);
        /* int32 height = 6; */
        if (message.height !== 0)
            writer.tag(6, WireType.Varint).int32(message.height);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message project.v2.Project.RegionOfInterest.Rect
 */
export const Project_RegionOfInterest_Rect = new Project_RegionOfInterest_Rect$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Project_Namespace$Type extends MessageType<Project_Namespace> {
    constructor() {
        super("project.v2.Project.Namespace", [
            { no: 1, name: "uuid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Project_Namespace>): Project_Namespace {
        const message = { uuid: "", name: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Project_Namespace>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Project_Namespace): Project_Namespace {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string uuid */ 1:
                    message.uuid = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Project_Namespace, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string uuid = 1; */
        if (message.uuid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.uuid);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message project.v2.Project.Namespace
 */
export const Project_Namespace = new Project_Namespace$Type();
