/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FileSelector: typeof import('./src/components/sidebar/FileSelector.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    RatioSelector: typeof import('./src/components/sidebar/RatioSelector.vue')['default']
    RectItem: typeof import('./src/components/sidebar/RectItem.vue')['default']
    RectList: typeof import('./src/components/sidebar/RectList.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Toolbar: typeof import('./src/components/sidebar/Toolbar.vue')['default']
  }
}
