name: Template Creator CI

on:
  push:
    branches:
      - master
    paths:
      - "template-creator"
  pull_request:
    branches:
      - master
    paths:
      - "template-creator"
  workflow_dispatch:

defaults:
  run:
    working-directory:  template-creator

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.repository, 'pboymt')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm" # Set this to npm, yarn or pnp

      - name: Install dependencies (ubuntu only)
        if: startsWith(matrix.os, 'ubuntu-')
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Build the frontend
        run: npm run build

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # This only works if your workflow triggers on new tags.
          releaseName: "Mayer Template Creator v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "See the assets to download and install this version."
          releaseDraft: false
          prerelease: true
